### ISSUE TITLE
Not working any more => http has to be changed to https

### ISSUE THREAD

**Issue by woodyc79** [alexchantastic/alfred-lipsum-workflow#1]
Hello!
As this workflow was not working any more, i took a look at it and found out that the URL in the PHP files has to be changed from 
http://lipsum.com/feed/json
to
https://lipsum.com/feed/json

Kind regards,
Chris

**Comment by alexchantastic** [comment]
This workflow no longer uses the API from lipsum.com, but rather a local script that generates the filler text. Can you try upgrading and seeing if it works for you?

**Comment by alexchantastic** [comment]
@woodyc79 this has been open for a while and this issue shouldn't be present since the v2.0.0 release. Let me know if you are still running into issues. Closing this issue for now.
