### ISSUE TITLE
The numbers in the search query are not accepted

### ISSUE THREAD

**Issue by DragNet2** [alexchantastic/alfred-lipsum-workflow#12]
For some reason when I try to specify a number in the "Lorem Words" search query, it forwards me to the Google search (look at the video attached).

https://github.com/alexchantastic/alfred-lipsum-workflow/assets/41149801/10cd1609-d00e-4059-bfcd-6b28d8687066

**Comment by alexchantastic** [comment]
Hi @DragNet2! Thanks for filing this issue. I'm not able to reproduce this on my end, but It seems like you've modified the workflow a bit. Can you export and attach the workflow here so I can test it out?

At a glance, it seems like the keyword you have set up is not matching up with what you are typing because the Google search as a result popping up is the default behavior when Alfred does not have a keyword to trigger off of.

**Comment by DragNet2** [comment]
The workflow did not work from the box, so I don't think you will find something in the attachment.

As you can see on the video, I don't use any keywords except the default ones.
1. Type "lorem"
2. Select "words" from the search results or type it manually after the Lorem word.
3. Try typing any number - no success since it forces Google search immediately after you type last "s" letter in the "words" word.

[Lorem Ipsum.zip](https://github.com/alexchantastic/alfred-lipsum-workflow/files/13792788/Lorem.Ipsum.zip)

**Comment by DragNet2** [comment]
Strange thing here - I just realized that the behavior changed since I sent you the initial video.

At the first video you can see, that the google appears only after I type space after the "lorem words", however right now google appears when I type the last "s" in the "words" word.

https://github.com/alexchantastic/alfred-lipsum-workflow/assets/41149801/8d23d83e-8007-4878-9c68-dcf0a942302b

**Comment by alexchantastic** [comment]
It looks like the workflow you're using is not the one I authored 😅. Check out the [releases](https://github.com/alexchantastic/alfred-lipsum-workflow/releases) page for the latest version.

**Comment by DragNet2** [comment]
Oooops )) It seems so. Thank you )
