### ISSUE TITLE
Generate lorem ipsum by character count?

### ISSUE THREAD

**Issue by richardsison** [alexchantastic/alfred-lipsum-workflow#2]
What are the chances of generating lorem ipsum by characters? Sometimes I need to limit a text field by characters and just want to see how long 280 characters is for example.

**Comment by alexchantastic** [comment]
Yes, I've been wanting to add this in for a while. I'll slot some time this or next week to implement.

**Comment by alexchantastic** [comment]
@richardsison I just released [v2.2.0](https://github.com/alexchantastic/alfred-lipsum-workflow/releases/tag/v2.2.0) with a character generator. Let me know if it works for you.
