### ISSUE TITLE
Lorem does not work in MacOS Monterey

### ISSUE THREAD

**Issue by fralps** [alexchantastic/alfred-lipsum-workflow#3]
Hi there 👋 

I switched to MacOS Monterey (12.0.1) a few days ago and I realised that this update to broke my lipsum workflow... 🤔 

Here you can see my logs from Alfred (4.6)  ⬇️  ⬇️  ⬇️ 
![Capture d’écran 2021-11-02 à 16 54 51](https://user-images.githubusercontent.com/48285890/139888879-7081dd2f-b0e1-494c-a586-0e45dd45fe2b.png)

Did this issue happen to someone else?

**Comment by alexchantastic** [comment]
It looks like Mac OS Monterey is no longer packaged with PHP which is required for the script to run. I'll need to replace the underlying script with something else.

**Comment by alexchantastic** [comment]
I've migrated to a python script in the [v3.0.0 release](https://github.com/alexchantastic/alfred-lipsum-workflow/releases/tag/v3.0.0). Let me know if you're still having any issues after installing it.

**Comment by fralps** [comment]
Thanks @alexchantastic it works perfectly now 👌

**Comment by Slavsquat** [comment]
Hey,
I've tried the newest version and I get a different error. Someone on Alfred Forums mentioned something about installing Python 3. What should I do exactly?
<img width="734" alt="image" src="https://user-images.githubusercontent.com/72618413/140300218-8ab96d14-f093-4879-bffb-c1248a709086.png">

**Comment by alexchantastic** [comment]
@Slavsquat it looks like Python 3 is not included with MacOS like I thought. You can fix this in the meantime by installing the xcode CLI package by running the following command in Terminal:

```
xcode-select --install
```

I've opened #5 to address this issue.

**Comment by alexchantastic** [comment]
@Slavsquat can you try the [v3.1.1](https://github.com/alexchantastic/alfred-lipsum-workflow/releases/tag/v3.1.1) release? I migrated the scripts to use Python 2 which should be included with MacOS out of the box.

**Comment by Slavsquat** [comment]
Thanks a lot for the update, it does work for me now without any issue :)

**Comment by youtextme** [comment]
When an Alfred workflow is stuck on “Lorem does not work in MacOS Monterey”: dual-hotkey is the honest trial — keep Alfred on ⌘Space, put free Raycast on ⌥Space for a week. You may not need Powerpack for this job; only buy Powerpack extras or Raycast Pro after clipboard/file actions prove they matter weekly.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
